"""initial

Revision ID: 3a413467497c
Revises: 
Create Date: 2025-09-18 21:22:44.373267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a413467497c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=120), nullable=False),
    sa.Column('producto', sa.String(length=120), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.Column('pagado_fecha', sa.DateTime(), nullable=True),
    sa.Column('enviado_fecha', sa.DateTime(), nullable=True),
    sa.Column('comprobante_path', sa.String(length=255), nullable=True),
    sa.Column('factura_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta')
    # ### end Alembic commands ###
